name: Publish to NPM and Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Build lib
        run: pnpm run build
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_UI_REACT }}
          access: 'public'

  deploy-storybook:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Build Storybook
        run: pnpm run build-storybook
      - name: Deploy Storybook to GitHub Pages
        run: pnpm run deploy-storybook
